### ISSUE TITLE
SCP-069 Doesn't work for me

### ISSUE THREAD

**Issue by oldboot6666** [SrLicht/SCP-069#3]
When using the plugin, it turned out that sсp-069 does not become the one he killed. Nothing happens, although it never happened before

**Comment by SrLicht** [comment]
Try this, and if it keeps happening could you give me a screenshot of your console?

[Scp069.zip](https://github.com/SrLicht/SCP-069/files/5832903/Scp069.zip)

**Comment by SrLicht** [comment]
You need Exiled 2.1.28.

**Comment by oldboot6666** [comment]
No errors were found in the console.
I have the latest version exiled

I use this plugin configuration:
https://user-images.githubusercontent.com/77626237/105041755-7163bc80-5a74-11eb-9d8a-ca9024903c5c.png

but nothing has changed, the problem remains the same

**Comment by oldboot6666** [comment]
so how to fix it?

**Comment by oldboot6666** [comment]
Sorry, I want to rephrase my question. The scp-069 plugin works as expected, but not for me (as a server creator). That is, other players can safely transform into other people, but this does not happen to me.

**Comment by SrLicht** [comment]
Well SCP-069 works perfectly on my server and you are the only one who has complained about this error, please test if any of the other plugins on your server are the reason for this inconvenience.
